## Loading Data

Loading data from [here](./Concepts%20-%20Linear%20Regression.ipynb)

In [14]:
import numpy as np

In [41]:
np.random.seed(10)
m = 100 #observations

X = 2 * np.random.rand(m,1)
y = 4 + 3 * X + np.random.randn(m,1)
bias_array = np.ones((m,1))
X_b = np.c_[bias_array,X]

## Batch Gradient Decent

When we either don't have a [normal equation](./Concepts%20-%20Linear%20Regression.ipynb) to directly minimize a cost function for estimating theta, we may need to find it iteratively. This is gradient decent.

As we adjust $\boldsymbol{\theta}$, the error will decrease as we get closer to a min, and higher as we get further from the min error. Gradient Decent simply looks the rate of change, or slope (calculated as the partial derivative), and then takes one step in the direct that reduces the error the most.

The best analogy is that you are decending a mountain on which you can only see 1 foot in front of you. You will look in all directions, and take a step in the direction that has the greatest decreased grade. If you continue this, you will eventually find your way to the bottom.

Problems with this include:
* this method may get you to a local min but not the global min
* learning rate is important. If you too low, you'll never reach min. If too high you'll bounce around above it.

*note* Learning rate is the size of the step you take

If the cost function is below:
$$(\frac{1}{m})\sum_{i=1}^{m}(\boldsymbol{\theta}^\intercal \mathbf{x}^{i} - y^{i})^{2} $$  

$$ MSE(\boldsymbol{\theta})$$

Then the partial deravitive can be found with
$$ \frac{\partial}{\partial\theta_{j}}MSE(\boldsymbol{\theta}) = (\frac{2}{m})\sum_{i=1}^{m}(\boldsymbol{\theta}^\intercal \mathbf{x}^{i} - y^{i}){x_j}^{i} $$

The above is for one direction, but you would need to create the full space around you to see which way is lowest. So you'll need to do for each possible direction to move theta (2 directions if $\theta$ is a scalar, 4 directions if $\boldsymbol{\theta}$ is a vector with 2 scalars, etc).

So you end up with a vector of gradients.

$$ \mathbf{\nabla_\theta} MSE(\boldsymbol{\theta}) = \begin{bmatrix} \frac{\partial}{\partial\theta_{0}}MSE(\boldsymbol{\theta}) \\ \frac{\partial}{\partial\theta_{1}}MSE(\boldsymbol{\theta}) \\ \vdots  \\ \frac{\partial}{\partial\theta_{n}}MSE(\boldsymbol{\theta}) \end{bmatrix} =  \frac{2}{m} \mathbf{X}^{\intercal} (\mathbf{X}\boldsymbol{\theta} - \mathbf{y})$$

Gradient decent will show you the steepest part, so your next step is simply a *negative* of the gradient scaled by the *learning rate* or $\eta$

In [43]:
eta = 0.1 #learning rate
n_iterations = 1000 #number of steps before settling on min

In [44]:
theta = np.random.rand(2,1) # start with a random weight, a randome place on the gradient space
theta

array([[0.02526395],
       [0.04919516]])

In [45]:
for step in range(n_iterations):
    gradients = 2/m *X_b.T.dot(X_b.dot(theta)-y) #calculate the full vector space of partial derivatives (gradients)
    theta = theta - eta * gradients

In [46]:
theta

array([[4.24963579],
       [2.81740108]])

The above theta is the same as was found using the normal equation [here](./Concepts%20-%20Linear%20Regression.ipynb)

## Stochastic Gradient Decent

The above equations use the entire training set to calculate each step. This can get computationally heavy. So you can use Stochastic Gradient Decent.

SGD looks at random instances and calculates the partial derivative of just one instance. This means it is very fast, but jumps around a lot as the random variation in the dataset will cause the cost function to also jump around a bit.

Because of how much the cost function will jump, SGD often reduces its learning rate as it gets closer, taking smaller and smaller steps. Overtime this means it will settle around a min rather than continually jumping in equal steps around it.

In [47]:
n_epochs = 50
t0, t1 = 5, 50 #These are the parameters used for the learning schedule

def learning_schedule(t):
    return t0 / (t + t1)

In [48]:
theta = np.random.randn(2,1)

In [49]:
for epoch in range(n_epochs):
    for i in range(m):
        random_index = np.random.randint(m)
        xi = X_b[random_index:random_index+1]
        yi = y[random_index:random_index+1]
        gradients = 2 * xi.T.dot(xi.dot(theta)-yi)
        eta = learning_schedule(epoch * m+ i)
        theta = theta - eta * gradients

In [50]:
theta

array([[4.19428856],
       [2.8757777 ]])

### Using Scikit-Learn

In [51]:
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor(max_iter=1000, tol=1e-3, penalty=None, eta0=0.1)
sgd_reg.fit(X,y.ravel())

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.1, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty=None, power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [52]:
sgd_reg.intercept_, sgd_reg.coef_

(array([4.20455032]), array([2.76081505]))