In [1]:
import numpy as np

## Tensor Defintions

* Scalar is a dimensionless number. ie. 3
* Vector is a "list" of numbers considered a row with one dimension, its length. ie. [1, 2, 3] 
* Matrix is a list of vectors (list of lists) with rows and columns, and thus two dimensions, its length and width. ie. [[1, 2, 3],[4, 5, 6]] This has a dimension of (2,3). That is, 2 rows and 3 columns.
* You can keep nesting these in which case we just call them tensors (Technically all of the above are tensors as well, just of specific names)

In [12]:
scalar = np.array(1)
print(type(scalar))
print(scalar.shape)

<class 'numpy.ndarray'>
()


In [13]:
vector = np.array([1, 2, 3])
print(type(vector))
vector.shape

<class 'numpy.ndarray'>


(3,)

In [14]:
matrix = np.array([[1,2,3],[4,5,6]])
print(type(matrix))
matrix.shape

<class 'numpy.ndarray'>


(2, 3)

## Element-wise Addition & Multiplication

* A matrix can be multiplied by a scalar by simply distributing the scalar to each matrix point
* Matrices of the same shape can be added across with like indexed positions
* Matrices of the same shape can be multiplied across with the like indexed positions

* Numpy assumes element-wise operations.

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a + 2

array([3, 4, 5])

In [21]:
a * 2

array([2, 4, 6])

In [24]:
matrix = np.array([a,b])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
matrix * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## Matrix Product (Dot Product)

The rules are different with Matrix Product
* The rows of the first matrix are multiplied by the columns of the second matrix. 
* * For this reason, the order of the matrices matters
* * For this reason, the column count of the first matrix must equal the row count of the second matrix. (Inside Numbers)
* * For this reason, the resulting matrix will have the dimensions equal the row count of the first matrix and the column count of the second matrix. (Outside Numbers
* So if the "inside numbers" of a matrix dimension match, they can be dot product
* The "outside numbers" of the matrix dimensions will be the final matrix dimensions.


In [26]:
matrix.shape

(2, 3)

In [30]:
matrix2 = np.array([[1,2,3, 4],[5,6, 7, 8],[9,10,11,12]])
matrix2.shape

(3, 4)

In [35]:
# From the dimensions, 
# they are compatible since 3 = 3
# Final dimesnions will be 2 x 4 (2 rows, 4 columns)

matrix_product = np.matmul(matrix, matrix2)
print(matrix_product)
print(matrix_product.shape)


[[ 38  44  50  56]
 [ 83  98 113 128]]
(2, 4)


## Transpose

This changes the shape of the data, so it generally only works if both matrices are arranged in rows before the transpose.

In [37]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])